# Generated by Django 5.0 on 2024-01-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
